# Generated by Django 4.2.23 on 2025-06-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_id',
            field=models.IntegerField(unique=True),
        ),
    ]
