# Generated by Django 4.2.23 on 2025-06-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_table_table_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_table', to='booking.table'),
            preserve_default=False,
        ),
    ]
