# Generated by Django 4.2.23 on 2025-06-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_reservation_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-time', '-date']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['-table_id']},
        ),
    ]
