# Generated by Django 4.2.23 on 2025-06-25 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_reservation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_guests',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
