# Generated by Django 4.2.23 on 2025-06-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_reservation_number_of_guests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['table_id']},
        ),
    ]
