# Generated by Django 4.2.23 on 2025-06-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_table_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='special_reqs',
            field=models.TextField(max_length=100),
        ),
    ]
