# Generated by Django 4.2.23 on 2025-06-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_reservation_special_reqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='special_reqs',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
