# Generated by Django 4.2.23 on 2025-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_reservation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='special_reqs',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
